language: java
jdk: openjdk8
install: true
branches:
  only:
  - master
  - /^(?i:release)-.+$/
  
addons:
  sonarcloud:
    organization: "komposten-github"
    token: $SONAR_TOKEN
    
script:
  - mvn clean install sonar:sonar
  